### ISSUE TITLE
fix: does not work with `pinia`

### ISSUE THREAD

**Issue by MartinMalinda** [nuxt-community/composition-api#111]
Error message: cannot read property 'req' of undefined

https://github.com/posva/pinia/issues/179

I'm not entirely sure why this happens. `setSSRContext` should just assign extra properties to the context, not replace it right?

**Comment by danielroe** [comment]
Thanks for your reports 😄

The issue is that `pinia` wants to [replace the setup function](https://github.com/posva/pinia/blob/5f96a1f6181ce41762fd6c8bb1448b2425b057f4/src/ssrPlugin.ts#L21) which conflicts with [what `nuxt-composition-api` does](https://github.com/nuxt-community/composition-api/blob/60459d14288402dc9a2be0dc4fb7996e32e292c8/src/plugin.js#L23).

**Comment by MartinMalinda** [comment]
I see, thanks! It would be great if these two great libraries would be friendly with each other:))

**Comment by DavidDomkar** [comment]
I just found out about this issue in my project. It would be nice if this module provided some way for other modules/user code to hook into the global setup function. For example, using custom nuxt hook similarly to how nuxt/components module does it: https://github.com/nuxt/components#library-authors

**Comment by danielroe** [comment]
I've submitted a PR to `pinia` that resolves this issue.

See https://github.com/posva/pinia/pull/180
