### ISSUE TITLE
fix: two versions of vue included in app

### ISSUE THREAD

**Issue by viktor-anyvan** [nuxt-community/composition-api#507]
After updating ^0.23.4  →  ^0.24.5 I see dev messages 2 times. Saw some braking changes for 0.24.0 (esm), do I have to make some changes? Not clear what was the change. Is this something I shouldn't worry about?

Thanks

vue.runtime.esm.js:8440
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.runtime.esm.js:8440
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

vue.runtime.common.dev.js:8403
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.runtime.common.dev.js:8412
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by viktor-anyvan** [comment]
"That message is pretty self-explanatory - it's just recommending you download Vue Devtools" not a helpful message. Why getting it twice is the question.

**Comment by viktor-anyvan** [comment]
Sure Daniel, is there a way to share somewhere else (don't want to be public)?

**Comment by viktor-anyvan** [comment]
@danielroe sent an email few days ago. Any updates?

**Comment by viktor-anyvan** [comment]
With my package.json would you be able to start a new project and see do you get the issue? Or how should we do it?

**Comment by TrungRueta** [comment]
@danielroe Hi Daniel,
Because author's topic no response, i create a repo to demoe issue here. I got same issue with him today when try setup new Nuxt and add nuxt-composition-api. Both Nuxt and plugin is fresh new ( no custom anything). Isuse can see after run `npm run dev`. See in devtool at homepage will have 2 production tip message come from 2 difference vue file. Look like Nuxt use esm file and plugin use common.dev file.

```
https://github.com/TrungRueta/dev-bug-composition-api-nuxt
```

![image](https://user-images.githubusercontent.com/12226007/124383097-e0686100-dcf4-11eb-8d9c-1043a8c83dc9.png)

Let me know if you need anything else.
Thanks for help!!

**Comment by danielroe** [comment]
Also note this reproduction: https://github.com/nonlinearcom/nuxt-use-test

**Comment by danielroe** [comment]
Fix released in `0.26.0` - let me know if that doesn't work for you.
